### ISSUE TITLE
Basically thanks you !

### ISSUE THREAD

**Issue by magnusseptim** [clowdhaus/eks-reference-architecture#1]
Hi

@bryantbiggs  I stumbled across your private cluster sample not so far ago and I was able to use it as a reference point with great effect.

As such, thanks you for your effort of sharing knowledge on a AWS/Terraform field.

And keep going !

**Comment by bryantbiggs** [comment]
Thank you @magnusseptim ❤️ - I hope to find some time to move the references further along and then look at integrating it with the upstream module. I get a lot of questions related to how to use this module to create "real" clusters (the examples in the `terraform-aws-eks` module are more for testing and not representative of how clusters typically look like in real environments). Stay tuned and any feedback is welcomed!

**Comment by magnusseptim** [comment]
@bryantbiggs Yeah, great to hear that.

Definitely looking forward for more architectural propositions of yours !
