### ISSUE TITLE
Error - error: CreateFile /proc/self/fd/63 during coredns deletion 

### ISSUE THREAD

**Issue by Sandy1438** [clowdhaus/eks-reference-architecture#10]
Terraform code fails during null_resource is getting executed. The problem is with shell substitution / Expansion of the below line:
kubectl --namespace kube-system delete deployment coredns --kubeconfig <(echo $KUBECONFIG | base64 --decode).

│ Error: local-exec provisioner error
│
│   with null_resource.remove_default_coredns_deployment,
│   on helm-provisioner.tf line 16, in resource "null_resource" "remove_default_coredns_deployment":
│   16:   provisioner "local-exec" {
│
│ Error running command 'kubectl --namespace kube-system delete deployment
│ coredns --kubeconfig <(echo $KUBECONFIG | base64 -d)
: The systematus 1. Output: error: CreateFile /proc/self/fd/63
│ cannot find the path specified.

It could  be nice if this command could modified.

BR,
Sandy

**Comment by bryantbiggs** [comment]
Hi Sandy - this is merely an example of how to achieve the reference architecture. Users may need to modify on their end (i.e. - if running on a Windows machine) to suite their setup
