### ISSUE TITLE
Thanks for the hint regarding vpc-cni before nodes for proper prefix delegation

### ISSUE THREAD

**Issue by trallnag** [clowdhaus/eks-reference-architecture#26]
Thanks for the hint regarding vpc-cni before nodes for proper prefix delegation

> If you find that your nodes are not being created with the correct number of max pods (i.e. - for m5.large, if you are seeing a max pods of 29 instead of 110), most likely the vpc-cni was not configured before the EC2 instances.

**Comment by bryantbiggs** [comment]
I will be updating the EKS module this week to correct for this FYI
